filter:
  paths:
    - "src/"
build:
  environment:
    php: '7.0'
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - [ -f composer.lock ] && rm composer.lock
      - composer self-update
  tests:
    override:
      - php-scrutinizer-run
      - vendor/bin/php-cs-fixer fix src --dry-run --rules=@PSR2
      -
        command: vendor/bin/phpunit --testdox --coverage-clover=clover-coverage
        coverage:
          file: clover-coverage
          format: clover