filter:
  paths:
    - "src/"
build:
  image: default-bionic
  environment:
    php: '8.2.1'
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - composer self-update
      - composer update
  tests:
    override:
      - php-scrutinizer-run
      - vendor/bin/php-cs-fixer fix src --dry-run --rules=@PSR2
      -
        command: vendor/bin/phpunit --testdox --coverage-clover=clover-coverage
        coverage:
          file: clover-coverage
          format: clover