os: linux

dist: xenial

language: php

matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      dist: bionic

branches:
  only:
    - master
    - develop

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/php-cs-fixer fix src --dry-run --rules=@PSR2
  - vendor/bin/phpunit --testdox

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

cache:
  directories:
    - vendor