language: php

php:
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
    - master
    - develop

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/php-cs-fixer fix src --dry-run --rules=@PSR2
  - vendor/bin/phpunit --testdox

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

cache:
  directories:
    - vendor